// This file is generated by npm run build:icons

export type IconName =
  | "camera-off"
  | "chevron-left"
  | "chevron-right"
  | "facebook"
  | "instagram"
  | "linkedin"
  | "minus"
  | "plus"
  | "shield-question"
  | "twitter"
  | "x"
  | "youtube";
